import { indexedDB, IDBKeyRange } from 'fake-indexeddb';
import fs from 'fs';
global.indexedDB = indexedDB; global.IDBKeyRange = IDBKeyRange;
global.window={addEventListener(){},scrollTo(){}};
global.document={querySelectorAll:()=>[],getElementById:()=>({addEventListener(){},classList:{add(){},remove(){},toggle(){}},style:{},focus(){},querySelector:()=>({addEventListener(){}}),getContext:()=>({clearRect(){},drawImage(){}}),value:''})};
global.FileReader=class{readAsDataURL(){}};
global.Image=class{};
const html=fs.readFileSync('index.html','utf8');
const script=html.split('<script>')[1].split('</script>')[0];
const test=`;(async()=>{
 const E=[],A=(c,m)=>c?console.log('PASS',m):(E.push(m),console.log('FAIL',m));
 await openDB();
 const c=await saveDraft('character',{title:'マシュ',outline:'盾の少女',charmPoint:'前髪',sexAppeal:'胸元',images:['data:img1','data:img2'],thumbnail:'data:img1'});
 A(c.projectId===null,'char draft projectId null (cross-project)');
 A(!!(c.id&&c.createdAt),'char draft has id+createdAt');
 const s=await saveDraft('story',{title:'序章',memo:'断片メモ',images:[],thumbnail:null});
 A(s.thumbnail===null,'story draft thumbnail optional null');
 const ch=await listDrafts('character'), st=await listDrafts('story');
 A(ch.length===1&&st.length===1,'drafts separated by kind');
 A(ch[0].charmPoint==='前髪','char fields persisted');
 const c2=await saveDraft('character',{id:c.id,title:'マシュ改',images:c.images,thumbnail:'data:img2'});
 A(c2.id===c.id,'update keeps id');
 const ch2=await listDrafts('character');
 A(ch2.length===1&&ch2[0].title==='マシュ改','update not duplicate');
 A(ch2[0].thumbnail==='data:img2','thumbnail updated');
 await deleteDraft('story',s.id);
 A((await listDrafts('story')).length===0,'delete works');
 console.log(E.length?'\\nFAILURES '+E.length:'\\nALL PASS');
})();`;
eval(script+test);
